name: Brute OS Plymouth Theme PKG BUILD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
             git \
             build-essential \
             devscripts \
             debhelper \
             cmake \
             debhelper-compat \
             extra-cmake-modules \
             pkg-config

    - name: Create Directory and pull source repository
      run: |
         mkdir -p /tmp/pkg_build/
         cd /tmp/pkg_build/
         git clone https://github.com/sys41x4/pkg_build_scripts.git
         git clone https://gitlab.com/brute-os/packages/brute-os-plymouth-theme.git
         cd brute-os-plymouth-theme
         git checkout main

    - name: Generate Debian package
      run: |
        cd /tmp/pkg_build/
        /tmp/pkg_build/pkg_build_scripts/deb/create_unsigned_debian_pkg.sh brute-os-plymouth-theme@all "Arijit Bhowmick" root

    - name: Get NEW Branch name
      run: |
        cd /tmp/pkg_build/
        branch_name="$(./pkg_build_scripts/deb/get_pkg_BUILD_version.sh BUILD_brute-os-plymouth-theme/BUILD/)"
        echo "branch_name=$branch_name" >> $GITHUB_ENV

    - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: brute-os-plymouth-theme_UNSIGNED
          path: /tmp/pkg_build/BUILD_brute-os-plymouth-theme/
